### PR TITLE
Create a Promise implementation that uses underlying JS Promises to interop with JS and CompletableDeferred on the rest of the targets

### PR DESCRIPTION
**Pull request by soywiz**
@lemkoleg

### CODE REVIEW

**Comment by lemkoleg** [comment]
Hello, Carlos.
I am trying to create a promise this way and causing errors in JS. Am I
doing something wrong?

suspend fun promise(time: Long): Promise<Unit>{
    val del = TimeSpan(100.0)
    return GlobalScope.launch {
        while (!isAwaited && time > DateTime.nowUnixLong()) {
            delay(del)
        }}.toPromise()
}

**Comment by lemkoleg** [comment]
If I do this,
I get a compiler warning about the inability to use the osuspend function

suspend fun promise(time: Long): Promise<Unit>{
    val del = TimeSpan(100.0)
    return Promise { _, _ ->  while (!isAwaited && time >
DateTime.nowUnixLong()) {
        delay(del)    \\Suspension functions can be called only within
coroutine body
    }}
}



вт, 5 мая 2020 г. в 19:33, Олег Лемко <lemkoleg82@gmail.com>:

> Hello, Carlos.
> I am trying to create a promise this way and causing errors in JS. Am I
> doing something wrong?
>
> suspend fun promise(time: Long): Promise<Unit>{
>     val del = TimeSpan(100.0)
>     return GlobalScope.launch {
>         while (!isAwaited && time > DateTime.nowUnixLong()) {
>             delay(del)
>         }}.toPromise()
> }
>
>
>

**Comment by soywiz** [comment]
If you plan to call it from JS, remove the `suspend` modifier and do not use `Long`. I provided two `.toPromise()` one without parameters and suspend and other with a CoroutineContext not being suspend.
Use the variant from the first comment, remove suspend, replace Long with Double in the signature then replace delay(del) with delay(del.toLong())  and change toPromise() with toPromise(EmptyCoroutineContext)

**Comment by lemkoleg** [comment]
Earned! Thank you very much, Carlos. I understand that most likely
this is not possible, but it may be possible to call Promise.await ()
in JS?


вт, 5 мая 2020 г. в 19:50, Carlos Ballesteros Velasco <
notifications@github.com>:

**Comment by soywiz** [comment]
Yes, it is possible:

JS code:
```js
async function jsFunction(){
    await promise(10)
}
```

**Comment by lemkoleg** [comment]
Thank you, Carlos.

вт, 5 мая 2020 г., 20:32 Carlos Ballesteros Velasco <
notifications@github.com>:

**Comment by lemkoleg** [comment]
I meant using .await in common module

вт, 5 мая 2020 г. в 20:32, Carlos Ballesteros Velasco <
notifications@github.com>:

**Comment by lemkoleg** [comment]
Tell me Carlos. I have a background process that checks for new
responses in the input message queue (WebSocket puts them in the
queue) and their parsing.
Should I use Worker for this? As far as I know, Workers cannot
use global objects (the queue is a global object). This is true?


вт, 5 мая 2020 г. в 20:32, Carlos Ballesteros Velasco <
notifications@github.com>:

**Comment by soywiz** [comment]
Hey @lemkoleg this is GitHub issues and some people is subscribed and get emails for each comment, this channel is for reporting bugs and feature requests. If you want support, I'd suggest you to use slack. You can ask here and we will try to help you: https://slack.soywiz.com/

Best regards

**Comment by lemkoleg** [comment]
Forgive me.  I thought our correspondence was personal

вт, 5 мая 2020 г., 22:53 Carlos Ballesteros Velasco <
notifications@github.com>:

**Pull request merged**
